### ISSUE TITLE
Copy overlay div is positioned at the center of the screen messes with the hover effect

### ISSUE THREAD

**Issue by zolomohan** [zolomohan/palette#2]
![issue](https://user-images.githubusercontent.com/45763204/67426633-21d7dc00-f5f8-11e9-8d2b-df8e0372c2b9.gif)

When hovered at the center of the screen, the hover effect i.e., hover to display copy button is triggered for the last box.

This happens because, all the copy overlay divs of the color boxes are stacked at the center of the screen. The last overlay is at the top thus triggering the hover effect for the last color box.

**Comment by zolomohan** [comment]
![image](https://user-images.githubusercontent.com/45763204/67427294-7596f500-f5f9-11e9-8a89-0eecd965bf73.png)

**Comment by luismanfroni** [comment]
Solving this issue
